FROM rockylinux:9

# Instalar Python 3 usando dnf
RUN dnf install -y python3 && dnf clean all

# Crear directorio de trabajo inside del contenedor
WORKDIR /app

# Copiar el script de Python que creamos antes
COPY server.py .

# Exponer el puerto del backend
EXPOSE 5000

# Comando para arrancar el backend
CMD ["python3", "server.py"]
